// WalkthroughData.swift
// Static chapter and section structure for the TotK walkthrough.
// Content populated from chunks.jsonl via keyword search.
// Re-generate with: python -m pipeline.generate_walkthrough_content

import Foundation

enum ChapterCategory: String, CaseIterable {
    case mainQuest = "Main Quest"
    case sideContent = "Side Content"
    case reference = "Reference"
}

struct WalkthroughSection: Identifiable, Hashable {
    let id: String
    let title: String
    var content: String = ""
}

struct WalkthroughChapter: Identifiable {
    let id: String
    let title: String
    let category: ChapterCategory
    let icon: String
    let sections: [WalkthroughSection]
}

enum WalkthroughData {
    static let chapters: [WalkthroughChapter] = [

        // MARK: - Main Quest

        WalkthroughChapter(
            id: "getting-started",
            title: "Getting Started",
            category: .mainQuest,
            icon: "star.circle",
            sections: [
            WalkthroughSection(id: "gs-controls", title: "Controls & UI Overview", content: "The is an Item in . Location and Uses The Purah Pad is a device created by the Sheikah researchers, Purah and Robbie, to be used by adventurers. It was developed after Robbie moved to the Hateno Ancient Tech Lab to assist Purah with her research. Robbie is upset that it is not named after him, despite his contributions to its development. It has a thin, tablet-like design, with gold and crimson colorations.\n\nas a Sinkhole, a lake at a certain time, or a view from a particular location. Map The Purah Pad's Map is comprised of three layers, the Sky, the Surface, and the Depths. The displayed layer can be switched with the Up and Down buttons on the D-Pad. The Sky layer is unlocked by default, and the Surface and Depths layers are unlocked once Link reaches them for the first time.\n\nare recurring Items in . Armors go unnamed in . They are pieces of Clothing and protective covering that Link can wear. Location and Uses Suits of Armor can be found in Hyrule Castle. They are equipped with Spears. Armor serves a variety of purposes, primarily to provide Link with defensive padding, allowing him to endure more damage. Damage numbers are shown numerically in , albeit indirectly."),
            WalkthroughSection(id: "gs-abilities", title: "Link's Core Abilities", content: "catch her, he is unable to reach her in time. As she falls, the Secret Stone she picked up begins to glow brightly, and she vanishes in a flash of golden light. Link is then caught by the Right Arm and transported elsewhere by its magic. The Great Sky Island Some time later, Link comes to in the Room of Awakening with his Armor missing and decayed arm replaced by the Right Arm.\n\nUltrahand is a recurring ability in . Overview Ultrahand is an Ancient Power that Link obtains from Rauru in Ukouh Shrine. It allows Link to stick Objects together or move them. When Ultrahand is used, Link has the option to move Objects around or rotate them either vertically or horizontally. If Link moves an Object close to another one, he can bind them together with a green viscous substance.\n\nOverview thumb|left|250px|alt= A screenshot of Rauru as a Spirit outside the Temple of Time. Text on-screen displays his name, along with the title \"Source of the Right Arm\".|Rauru's introduction After receiving the Purah Pad from a Steward Construct, Link is told that Zelda is waiting for him in the Temple of Time on the Great Sky Island."),
            WalkthroughSection(id: "gs-tips", title: "Early Game Tips", content: "are recurring Items in . Location and Uses Copious Seafood Skewers can be made by Cooking four different types of Seafood in a Cooking Pot. When eaten, they heal some of Link's Hearts. Despite being a heap of random Items shoved onto a skewer, they are known to be a tasty dish. Because of their specified recipe, very few variations of Copious Seafood Skewers exist.\n\nare recurring Meals in . Location and Uses Creamy Seafood Soups are made in Cooking Pots by Cooking any seafood, Fresh Milk, Rock Salt, and any Vegetable, herb, or Flower together. However, if Endura Carrots, Swift Carrots, or Fortified Pumpkins are used, the resulting dish will be Veggie Cream Soup.\n\nwill always result in Rock-Hard Food regardless of what other ingredients are used. If a Fairy is used as an \"ingredient\" when cooking a Meal, it will use its magic to aid the cooking process, significantly increasing the amount of Hearts recovered. Elixirs will also provide Link with Added Effects and can replenish health. They are made by cooking critters together with Monster Parts in a Cooking Pot.\n\nare recurring Items in . Location and Uses Gourmet Meat and Seafood Fries are meals made by Cooking either Raw Gourmet Meat or"),
            ]
        ),

        WalkthroughChapter(
            id: "great-sky-island",
            title: "The Great Sky Island",
            category: .mainQuest,
            icon: "cloud",
            sections: [
            WalkthroughSection(id: "gsi-wake", title: "Waking Up", content: "The Great Sky Island is a location in . Features and Overview The Great Sky Island is a large mass of land composed by several Sky Islands found in the Central Hyrule Sky. It is home to many Constructs who protect and tend to its grounds. On its northern end sits a large tower known as the Temple of Time.\n\nfrees the other five Sages. He tells Link to meet \"someone\" waiting at the Temple of Time before facing Ganondorf. This person turns out to be Sheik, who reveals himself as none other than Princess Zelda, the seventh Sage. Unfortunately, by revealing herself to Link, Princess Zelda exposes herself to Ganondorf, who subsequently captures her and takes her to his Castle.\n\nThe is a location and Object in . Features and Overview The Sacred Tree of the Zonai is a large Tree found atop the highest Sky Island on the Great Sky Island. It is located directly above the Room of Awakening. In the eponymous Voice Memory \"Sacred Tree of the Zonai\", Rauru reveals that the Sacred Tree shares a connection with the Zonai people, prospering when they do.\n\n, also known as Right-Hand Abilities, are abilities in . Overview Ancient Powers are abilities that originate from antiquity."),
            WalkthroughSection(id: "gsi-ukouh", title: "Ukouh Shrine — Ultrahand", content: ", designated by the trial name The Ability to Create, is a Shrine of Light in . Entrance to the Shrine The Ukouh Shrine is located in the western part of the Garden of Time on the Great Sky Island, due west of the Temple of Time. In order to enter the Shrine of Light, Link must interact with the Ukouh Shrine's entrance.\n\nUltrahand is a recurring ability in . Overview Ultrahand is an Ancient Power that Link obtains from Rauru in Ukouh Shrine. It allows Link to stick Objects together or move them. When Ultrahand is used, Link has the option to move Objects around or rotate them either vertically or horizontally. If Link moves an Object close to another one, he can bind them together with a green viscous substance.\n\nOverview thumb|left|250px|alt= A screenshot of Rauru as a Spirit outside the Temple of Time. Text on-screen displays his name, along with the title \"Source of the Right Arm\".|Rauru's introduction After receiving the Purah Pad from a Steward Construct, Link is told that Zelda is waiting for him in the Temple of Time on the Great Sky Island.\n\nSoldier Construct Ii Horn is a Material in Tears of the Kingdom. A sharp, hooked horn dropped from a Soldier Construct II."),
            WalkthroughSection(id: "gsi-inisa", title: "In-isa Shrine — Fuse", content: ", designated by the trial name The Ability to Combine, is a Shrine of Light in . Entrance to the Shrine The In-isa Shrine is located in the southwestern part of the Garden of Time on the Great Sky Island. In order to enter the Shrine of Light, Link must interact with the In-isa Shrine's entrance.\n\nare recurring Items in . Location and Uses Flints can be found after breaking Ore Deposits, Luminous Stone Deposits, and Rare Ore Deposits. Striking pieces of Flint with metal Weapons causes the former to ignite. This can be used to create Campfire by dropping a piece near some Wood before striking it. It can be used to relight extinguished Campfires as well, including those under Cooking Pots.\n\n, also known as , and Bone Weap. Prof., is a recurring Set Bonus in . Overview Bone Atk. Up is a Set Bonus that increases the attack power of bone Weapons and Bows by 80%. This boost stacks multiplicatively with the Attack Up Effect. The following Weapons are considered to be bone Weapons or Bows in : Bone Atk. Up is granted by the Radiant Attire (★★) and the Phantom Ganon Set.\n\nweight increased further when he was appointed as a Champion. In the present, Yunobo now wields a Boulder Breaker of his own."),
            WalkthroughSection(id: "gsi-gutanbac", title: "Gutanbac Shrine — Ascend", content: ", designated by the trial name The Ability to Rise, is a Shrine of Light in . Entrance to the Shrine The Gutanbac Shrine is located in the eastern part of the Garden of Time on the Great Sky Island between the entrances to the Bottomless Cave. In order to enter the Shrine of Light, Link must interact with the Gutanbac Shrine's entrance.\n\nare locations in . Features and Overview Ascend Access Points are Zonai Ruins found throughout the Depths. There are sixteen Ascend Access Points in total. Each Ascend Access Point consists of a slightly raised square stone platform with stairs on each side leading up to it. On each corner, there is a pillar with a light source on top.\n\nis a recurring ability in . Overview Ascend is an Ancient Power that Link can use while underneath terrain or buildings so long as the targeted surfaces of both where Link enters and exit are relatively flat, he is close enough to the surface where he enters, and nothing would obstruct him on the other side. This is indicated via the portal turning green.\n\nThe , designated by the trial name Bridging the Sands, is a Shrine of Light in . Entrance to the Shrine The Kudanisar Shrine is a Shrine of Light on the Surface."),
            WalkthroughSection(id: "gsi-nachoyah", title: "Nachoyah Shrine — Recall", content: ", designated by the trial name The Ability to Rewind, is a Shrine of Light in . Entrance to the Shrine The Nachoyah Shrine is located above the Room of Awakening on the Great Sky Island. After Link enters the Temple of Time and receives the Recall ability from Zelda, the Spirit of Rauru guides him to the Nachoyah Shrine to receive the Great Sky Island's fourth Light of Blessing.\n\nat which point he disappears once more. With Recall, Link is able to reverse the gears within the Temple of Time, allowing him to access the upper chamber. There, he finds a Challenge Door, which will drain his Hearts as he pushes it.\n\nbeen a reflection of her will rather than Zelda herself. When Link attempts to open the rear doors of the Temple, Rauru informs him that he is still weak from his encounter with Ganondorf and that he must recover some strength before he can open it.\n\nis a recurring ability in . Overview Recall is an Ancient Power that allows its user to stop Objects in motion and reverse their trajectory. In Zelda's Memories from the Era of Foundation, both she and Sonia can be seen using Recall with the power granted to them by their Secret Stones of Time."),
            WalkthroughSection(id: "gsi-temple", title: "Reach the Temple of Time", content: "of Time there is a large Goddess Statue surrounded by six smaller Goddess Statues. Link can pray at this Goddess Statue and exchange four Spirit Orbs for either a Heart Container or a Stamina Vessel. To either side of the Goddess Statue are two Tombstones belonging to unknown decedents. On the rear side of the Temple of Time there is a symbol of the Triforce bearing the Crests of Din, Nayru, and Farore.\n\nThe is a recurring location in . Features and Overview During the Era of Chaos, a group of powerful sorcerers known as the Dark Interlopers waged a Battle for the Sacred Realm against the people of Hyrule to seize the Triforce."),
            WalkthroughSection(id: "gsi-descent", title: "Descend to Hyrule", content: "are recurring Items in . Location and Uses The Paraglider is first seen after Link activates the Great Plateau Tower and descends back to the ground. There, he is met by the Old Man, who is investigating the sudden appearance of Sheikah Towers across Hyrule.\n\nis a location in , serving as both the first and final area of the game. Features and Overview Beneath Hyrule Castle is a forbidden zone that descends into the very deepest part of Hyrule's Depths. A Stone Tablet in the Royal Hidden Passage indicates that the area beneath the castle was originally accessible through the passage.\n\nis a recurring Korok Seed Puzzle in . Dive Through the Ring goes unnamed in . Overview Dive Through the Ring is a variety of Korok Seed Puzzle found on bodies of Water throughout Hyrule. They involve a Circle of plants, such as Lily Pads or seaweed, located below a ledge. When Link dives through this Circle, a Korok will appear and give him a Korok Seed.\n\nEmptiness where Null resided into the larger world that Hyrule resides in; which begins a history spanning three separate timelines."),
            ]
        ),

        WalkthroughChapter(
            id: "arriving-in-hyrule",
            title: "Arriving in Hyrule",
            category: .mainQuest,
            icon: "mappin.circle",
            sections: [
            WalkthroughSection(id: "aih-lookout", title: "Lookout Landing", content: "is a location in . Features and Overview Lookout Landing is a fortified settlement located in the center of Hyrule Field, next to a Skyview Tower. It is built at the site of 's Sacred Ground Ruins. It is the base of operations for the Zonai Survey Team. In the northwestern corner is the Lookout Landing Well. Areas Mubs' General Store Alongside the Lookout Landing Armor Shop, Mubs also runs a General Store.\n\nThe is a location in . Features and Overview The Lookout Landing Armor Shop is an Armor Shop ran by Mubs in Lookout Landing. She also runs a parallel General Store with everyday goods instead of Armors. When Link completes one of the four \"Regional Phenomena\" Main Quests, the Lookout Landing Armor Shop and Mubs' General Store both are expanded with the help of Lookout Landing's Carpenter Karson Initially, Mubs will o\n\nis a location in . Features and Overview The Lookout Landing Well is a Well on the northeastern side of Lookout Landing. Though it is mostly featureless, there is a Cracked Wall on its southwestern side that rushing Water flows out from. Breaking the Wall reveals a passageway small enough for Link to Crouch through, at the end of which is a second chamber."),
            WalkthroughSection(id: "aih-shelter", title: "Emergency Shelter", content: "The is a recurring location in . The Hyrule Castle Underground goes unnamed in . Features and Overview The Hyrule Castle Underground consists of the portion of Hyrule Castle that is located below its main structure. It previously hosted mining operations in the East Passage and West Passage, and the Lockup housed the prisoners of Hyrule Castle.\n\nThe is a location in . Features and Overview The Royal Hidden Passage is a series of tunnels and underground structures that lead from Hyrule Castle to the Emergency Shelter. It can be accessed via hatches located in the Observation Room and near the Guards' Chamber.\n\nRoom of Awakening atop the Great Sky Island. The Imprisoning War thumb|250px|Rauru seals the Demon King Beneath Hyrule Castle is seen again in \"The Imprisoning War\" Memory. In the distant past, Rauru leads the Six Sages in a battle against Demon King Ganondorf to bring an end to the Imprisoning War.\n\nOverview Upon hearing Link's story during the \"To the Kingdom of Hyrule\" Main Quest, Purah determines that the events of the Upheaval must be connected to the mummy he and Zelda encountered Beneath Hyrule Castle."),
            WalkthroughSection(id: "aih-camera", title: "Camera Work in the Depths", content: "Overview After Link starts the \"Regional Phenomena\" Main Quest, Josha will go to meet Robbie at her lab in Lookout Landing. The two can then be found arguing with each other. When Link approaches them, Robbie comments on how nice the day has been. Noticing Link, Robbie makes a remark about his Purah Pad and its development.\n\nthe Hyrule Field Chasm. Josha expresses her excitement to see Link's Picture, and she asks him to take care of Robbie as well. Following this conversation, \"Camera Work in the Depths\" will begin. At the Hyrule Field Chasm, Link will discover that Robbie has already descended into the Depths. At the bottom of the Chasm, he will find Ponnick looking for Robbie.\n\nThe Depths are a location in . Features and Overview The Depths are a colossal network of caverns extending deep underneath Hyrule. They are accessed via the Chasms present on the surface, which are easily identified by the Gloom surrounding them. The Depths are extremely dark, making items that create light such as Brightbloom Seeds, Giant Brightbloom Seeds, or Lights valuable when exploring them.\n\nThe are a location in . Features and Overview The Gerudo Desert Depths are an area in the Depths located below th"),
            WalkthroughSection(id: "aih-castle", title: "Infiltrating Hyrule Castle", content: "that their combined efforts will lead them to Zelda. At this point, \"Regional Phenomena\" will begin. thumb|right|320px|alt= A screenshot of the floating portion of Hyrule Castle during a Blood Moon. A figure that appears to be Princess Zelda stands on, the Sanctum visible behind her.|The impostor Zelda outside Hyrule Castle After completing \"Tulin of Rito Village\", \"Yunobo of Goron City\", \"Sidon of the Zora\", and \"Ri\n\nis a recurring location in . Features and Overview Hyrule Castle Moat is a body of Water that surrounds Hyrule Castle in Hyrule Field. Hyrule Castle Moat is a deep, fast-flowing Water body encircling Hyrule Castle, located in northern Hyrule Field. It feeds into the Hylia and Regencia Rivers to the east and west respectively. A large bridge crosses the south of the Moat, providing access to the Hyrule Castle Gate.\n\nis a location in , serving as both the first and final area of the game. Features and Overview Beneath Hyrule Castle is a forbidden zone that descends into the very deepest part of Hyrule's Depths. A Stone Tablet in the Royal Hidden Passage indicates that the area beneath the castle was originally accessible through the passage."),
            WalkthroughSection(id: "aih-phenomena", title: "The Regional Phenomena", content: "Overview During the \"Crisis at Hyrule Castle\" Main Quest, Purah asks Link to start investigating the strange phenomena that has appeared throughout Hyrule as part of the Upheaval, believing that it could help them locate Princess Zelda. After he has activated the Lookout Landing Skyview Tower and collected its Map data, Purah asks to see his Purah Pad.\n\nThe are a recurring location in . Features and Overview The Sage Temple Ruins are the half-sunken remains of the Sage Temple located along the Regencia River in Hyrule Field. Scattered around the Ruins are a number of Barrels, in which Link can find Hylian Shrooms and Apples. Two broken wagons can be found in the Ruins, which can be searched for Materials.\n\nDemon King Ganondorf is a recurring Boss in . Biography Demon King Ganondorf is the form assumed by Ganondorf after obtaining his Secret Stone, stolen from Sonia. After becoming the Demon King, he created a swarm of Monsters and attacked Hyrule Kingdom and its allies, which started the Imprisoning War. At the end of the War, the Six Sages confronted him.\n\ncapable of rolling up the sides of the room to strike the Gloom Rocks on its ceiling."),
            ]
        ),

        WalkthroughChapter(
            id: "wind-temple",
            title: "Rito Village & the Wind Temple",
            category: .mainQuest,
            icon: "wind",
            sections: [
            WalkthroughSection(id: "wt-rito", title: "Reach Rito Village", content: "is a recurring location in . Features and Overview Rito Village is a settlement located on an island at the center of Lake Totori on the Tabantha Frontier. The Village was built around a giant stone pillar, with a vertical construction that is suited to the Rito's ability to fly. A small grove of Cedar Trees can be found below the Village proper. Several bridges also connect Rito Village to Rito Stable nearby.\n\nOverview As part of the \"Regional Phenomena\" Main Quest, Purah asks Link to investigate strange happenings caused by the Upheaval throughout Hyrule as part of their efforts to locate Princess Zelda. Josha suggests that he visit Rito Village first, claiming to have heard a rumor that Zelda was sighted there. thumb|left|250px|alt= A screenshot of Tulin with his wings outstretched at Revali's Landing."),
            WalkthroughSection(id: "wt-tulin", title: "Tulin of Rito Village", content: "Overview As part of the \"Regional Phenomena\" Main Quest, Purah asks Link to investigate strange happenings caused by the Upheaval throughout Hyrule as part of their efforts to locate Princess Zelda. Josha suggests that he visit Rito Village first, claiming to have heard a rumor that Zelda was sighted there. thumb|left|250px|alt= A screenshot of Tulin with his wings outstretched at Revali's Landing.\n\nTeba moves away from this topic, asking Link what has brought him to Rito Village. He and Saki are shocked to hear the state of Hyrule Castle. While Teba is disturbed that Zelda's disappearance could be related to the Upheaval, all adult Rito are unable to contribute to the search due to the need to search for Food."),
            WalkthroughSection(id: "wt-storm", title: "Approach the Storm", content: "are a recurring Weather mechanic in . Blizzards go unnamed in and . Overview Blizzards occur in certain areas of Frozen Hyrule. While present, Snow falls and harsh gusts of Wind that cover the screen and damage the Links if they are not in a Cave intermittently appear. Blizzards are a common Weather event in Freezing Climates, particularly on Mount Lanayru, the Hebra Mountains, and the Gerudo Highlands.\n\nis a recurring character in . Biography Baumar is a Hylian who travels with his Horse, Bamboo, while carrying a Fisherman's Shield and a Traveler's Sword. The pair travel a portion of the Hilltop High Road between Serenne Stable and Snowfield Stable. When Baumar was a child, he almost got lost up in the Hebra Mountains. While a shield surfer saved him, Baumar has trouble recall his name.\n\nThe , also known as the , is a recurring location in . Features and Overview N. Tabantha Snowfield is located in the Tabantha Tundra, along the northern border of Hyrule. It is a flat expanse that is covered by Snow, surrounded by the Hebra Mountains and Mount Drena. The North Lomei Labyrinth is also accessible through the Snowfield.\n\nThe is a location in . Features and Overview The Rising Island Chain"),
            WalkthroughSection(id: "wt-temple", title: "Wind Temple — Puzzles", content: "The , also known as the Stormwind Ark, is a recurring Dungeon and Stage in . Overview The Wind Temple and the Earth Temple were built in order to protect the Master Sword's power to repel evil, by means of providing a place for the two Sages to conduct their prayers to the Golden Goddesses. The prayer song for the Sage of Wind was the Wind God's Aria.\n\nthe Temple's depths and has small sections that branch off the main shaft. At the bottom of this shaft is a large propelling Fan that periodically turns on and off after being reactivated. Link makes constant use of several tools within the Wind Temple, primarily the Hookshot, the Iron Boots, and the Deku Leaf.\n\nis a location in . Features and Overview Wind Temple 1F encompasses the deck and surrounding area of the Stormwind Ark. It features a Terminal that controls a hatch holding Colgera, the source of the Blizzard plaguing the Hebra Region. However, this hatch is blocked by five turbine-shaped Locks which must be activated with Tulin's Power of Wind.\n\nis a location in . Features and Overview Wind Temple B1 is the middle segment of the Stormwind Ark.\n\nWhen defeated, Bokoblins may drop Bokoblin Fangs, Bokoblin Horns, and Bokoblin Guts."),
            WalkthroughSection(id: "wt-boss", title: "Boss: Colgera", content: "Colgera is a Boss in . Characteristics Colgeras are massive worm-like creatures reminiscent of Molgera, with a jagged layer of ice serving as armor for them. They have five eyes, large pincers, and a pair of wings on three of their body segments. One is responsible for the Extreme Cold Snap affecting the Hebra region.\n\nColgera is a Monster in Tears of the Kingdom. The culprit behind the blizzard that plagued the Hebra region. This huge beast harnesses wind to produce strong updrafts and lift itself aloft. The jagged layer of ice covering its body serves as a protective shield and allows it to launch frozen spikes at its foes. It can be found in: Wind Temple.\n\nresemble turbines. When Link and Tulin arrive, they are greeted by the disembodied voice of the Sage of Wind, who instructs them to use Tulin's Power of Wind in order to activate the Locks and release their respective seals on the hatch. Wind Temple 1F contains two Locks, Wind Temple B} contains another two, and Wind Temple B2 contains just one.\n\nOutfits at Madame Couture's. There are eight bosses in , six of which are incarnations of Malice.\n\nThe is a location in . Features and Overview The Rising Island Chain is the set of Sky Islan"),
            ]
        ),

        WalkthroughChapter(
            id: "water-temple",
            title: "Zora's Domain & the Water Temple",
            category: .mainQuest,
            icon: "drop",
            sections: [
            WalkthroughSection(id: "wat-zora", title: "Reach Zora's Domain", content: "heir. Aside from their princess Mipha, who was piloting Divine Beast Vah Ruta, Zora's Domain suffered no casualties as a result of the Great Calamity. Shortly before Link woke up from his Slumber of Restoration, Divine Beast Vah Ruta activated in the East Reservoir Lake for the first time since the Great Calamity, where it began to generate an endless amount of Water.\n\nyoung hero the Zora's Flippers out of gratitude. After Oren is trapped within a Painting and subsequently released, she vows to return to Zora's Domain once Link defeats Yuga and Ganon. thumb|left|250px|Mipha's Statue in Zora's Domain In , Zora's Domain is located within the Lanayru Great Spring and is the home of the Zora. Travelers entering the area by foot cross the Great Zora Bridge over Ruto Lake.\n\nThe is a location in . Features and Overview The Cave Under Zora's Domain can be found behind the Waterfall beneath the Great Zora Bridge in the Lanayru Great Spring. Its main feature is the Chasm Under Zora's Domain, which provides access to the Abandoned Lanayru Mine in the Depths.\n\nThe , also known as , King Zora's Chamber, the , and the Mine Keep, is a recurring location in ."),
            WalkthroughSection(id: "wat-sidon", title: "Sidon of the Zora", content: "Temple, a floating Sky Island from which Water flows.|The Water Temple Once Link confirms that he is ready, the pair will Swim up the Waterfall. Upon reaching the top, they will arrive at the Water Temple. Sidon is shocked that such a structure was above Zora's Domain. He then sees what he believes to be the origin of the Sludge.\n\ntime, she was a Sage who served Rauru, the first King of Hyrule. Based on Sidon's fluid movements as he fights, Qia declares her pride for him. She claims that Mucktorok was a servant of the Demon King Ganondorf that was sent to prevent him from obtaining her Secret Stone. She decides that it is important he knows the history of the Imprisoning War. Qia shows Link and Sidon a vision of Hyrule's earliest days.\n\nThe is an Item in . Location and Uses Link receives the Vow of Sidon, Sage of Water from Sidon after the two of them defeat Mucktorok in the Water Temple and Sidon awakens as the Sage of Water. The Vow of Sidon, Sage of Water allows Link to summon Sidon's Sage Avatar, which can be commanded to perform Sidon's Power of Water.\n\nDomain from when he was younger, claiming that he knows now that Link was not trying to steal her from him."),
            WalkthroughSection(id: "wat-sludge", title: "Clear the Sludge", content: "are recurring Bosses in . Characteristics Sludge Likes are Like Likes coated in a thick layer of Sludge, with only their fangs and the insides of their mouths visible through it. Their hides are a light shade of grey, and the areas around their jaws are a vibrant magenta with white flecks. They have two rows of fangs. Unlike their weaker cousins, they are capable of movement, giving them a fearsome reputation.\n\nOverview When Link first arrives in Zora's Domain, he finds that the Zora are recovering from a wave of Sludge the fell on them. Nearby, Yona can be found discussing the situation with Chroma and Khira. They reveal to her that they have run out of Splash Fruit while treating those affected by the Sludge and apologize.\n\nSludge Like is a Monster in Tears of the Kingdom. These sludge-loving Like Likes are nightmarishly mobile. They ooze sludge, and they use that sludge to move around, sometimes creeping into areas that other types of Like Likes tend to avoid. As if that weren't enough, they also spew sludge out of their maws to slow and capture prey. It can be found in: Lanayru Great Spring."),
            WalkthroughSection(id: "wat-temple", title: "Water Temple — Puzzles", content: "The Water Temple is a recurring Dungeon and location in . Overview Entrance to the Temple The ancient temple lies deep under the vast Lake Hylia. Guarded by the Zoras, it is considered a sacred temple that is used to worship the water spirits. The Water Temple is accessible after the young hero finds the Iron Boots in Ice Cavern.\n\nto access them. Boulders and most enemies are no longer found, except for two Spikes and nine completely new Stalfos. Two new features include a room with several Dodongos, plus several crates that are found throughout the dungeon. In the GameCube version of the , Link can complete the dungeon with an extra Small Key remaining.\n\nand a giant fish. Due to this, each Dungeon has its own music themes as well. The game also introduces another first in the series: an optional Dungeon. This Dungeon is named the Gerudo Training Ground. If he completes the challenges therein, Link will obtain the Ice Arrows, which are not necessary for completing his quest."),
            WalkthroughSection(id: "wat-boss", title: "Boss: Mucktorok", content: "Mucktoroks are Bosses in . Characteristics Mucktorok is a small Octorok-like creature, not much larger than a regular Octorok, which can create and control Sludge. It uses this Sludge to make a shark-like monster similar to a Gyorg, which it rides in battle. One Mucktorok is the source of the Sludge that is polluting the Lanayru Region.\n\nMucktorok is a Monster in Tears of the Kingdom. The culprit behind the sludge that plagued Zora's Domain. Despite its small size, it was able to produce a massive deluge of the substance, polluting the entire region. It can mold sludge into outer shells of various shapes, a technique it uses both to protect itself and attack its foes. It can be found in: Water Temple.\n\nOutfits at Madame Couture's. There are eight bosses in , six of which are incarnations of Malice. These are Waterblight Ganon, Fireblight Ganon, Windblight Ganon, Thunderblight Ganon, Calamity Ganon, and Dark Beast Ganon. The other two are Master Kohga and Monk Maz Koshia, the latter of whom can only be challenged when Downloadable Content pack is active.\n\nThe are a location in . Overview The Ancient Zora Waterworks are a Cave located at the bottom of East Reservoir Lake in the Lanayru Gre"),
            ]
        ),

        WalkthroughChapter(
            id: "fire-temple",
            title: "Goron City & the Fire Temple",
            category: .mainQuest,
            icon: "flame",
            sections: [
            WalkthroughSection(id: "ft-goron", title: "Reach Goron City", content: "\"little rock\". Yunobo recognizes that he is the source of the voice that has been calling out to them. Agraston reveals that he is Yunobo's distant ancestor, and in the past, he served the first King of Hyrule Rauru as a Sage. He is impressed by Yunobo's practice of using his own body as a weapon, referring to him as the pride of the Gorons.\n\nDarunia's son gives him the Goron Tunic, a tunic which lets Link endure the heat of Death Mountain Crater and the Fire Temple indefinitely, so long as it is worn. Once Link rescues all the Gorons from the Fire Temple, they will return to the city and thank Link for saving them."),
            WalkthroughSection(id: "ft-yunobo", title: "Yunobo of Goron City", content: "discern a voice telling them to come to a structure in the distance. Since the voice may be related to Zelda's location, Yunobo decides that they should follow it. thumb|right|320px|alt= A screenshot of the Fire Temple, an ancient structure surrounded by Lava in the Depths.|The Fire Temple When Link and Yunobo arrive at the structure, it is revealed that they have been traveling through Gorondia to reach the Fire Tem\n\nLink asks about Daruk, Yunobo reveals that he found Daruk's Training Journal, which describes both his love for delicious rocks and a good friend of his. He admits that since he does not have much of an appetite, he is considered to be scrawny for a Goron. When Link inquires about the Journal, Yunobo claims to have found it while cleaning in the Abandoned North Mine, and it is now in his House."),
            WalkthroughSection(id: "ft-mine", title: "YunoboCo HQ & the Mine", content: "The , also known as the Company Store, is a location in . Features and Overview The YunoboCo Mineral Market is situated where the New Road meets the Mountain Road northwest of the Southern Mine in Eldin Canyon. It is manned by Bladon and Shmid, who operate the two YunoboCo Stores inside. They sell Ores at half the price they can be bought for elsewhere.\n\n, also known as YunoboCo's HQ, is a location in . Features and Overview YunoboCo HQ is the headquarters of the mining corporation YunoboCo, built atop the North Mine in Eldin Canyon. It is connected to Goron City by a line of Rails. A small shop run by Dayto can be found beneath a tower with Yunobo's likeness carved onto it, selling Flamebreaker Armor.\n\n, also known as YunoboCo's Stores, are Shops in . Features and Overview YunoboCo Stores are Shops established by YunoboCo throughout Eldin Canyon. A total of four YunoboCo Stores can be found, two at the YunoboCo Mineral Market and two in Goron City. Since they source their Ores and Gems directly from YunoboCo, they are able to sell them at half the price they would normally be sold for.\n\nThe , also known as the , or the Northern Mining Site, is a recurring location in ."),
            WalkthroughSection(id: "ft-temple", title: "Fire Temple — Puzzles", content: "Most doors are blocked with iron bars, and the Big Key and Megaton Hammer come very early. New enemies include several Stalfos, Lizalfos (found in the boulder room) and even an Iron Knuckle. Enemies Entrance to the Temple The Fire Temple is located at the summit of the mountain in the Fire Realm. Link has to meet with Embrose to play the Song of Fire Restoration and open the way to the dungeon.\n\nThe , also known as the Mountain Temple, is a recurring Dungeon in . Overview Entrance to the Temple The Fire Temple is located deep within the Death Mountain Crater. It is only accessible to Link by use of the Goron Tunic, which is given to him by Darunia's son, Link, in the hopes that he will rescue the other Gorons. Being in an active volcano, the Fire Temple is filled with many lava pits including the boss room.\n\nThe is a location in . Features and Overview The Fire Temple 1F is the base floor of the Fire Temple. Its entrance hall is blocked by a Gloom Rock, which can only be destroyed with Yunobo's assistance. When Link and Yunobo first arrive, they spot Zelda advancing to the center of the floor, which is barred by a gate.\n\nThe is a location in . Features and Overview The Fire Temple 2F is"),
            WalkthroughSection(id: "ft-boss", title: "Boss: Marbled Gohma", content: "Marbled Gohmas are Bosses in . Characteristics Marbled Gohmas are four-legged, insectoid Monsters that are protected by rocky armor. Their Legs are covered in the Gloom Rocks that Marbled Rock Roast is mined from. Like all Gohmas, they have a single Eye that acts as their weakness. One Marbled Gohma created and spread Marbled Rock Roasts throughout the Eldin Region.\n\nMarbled Gohma is a Monster in Tears of the Kingdom. The culprit behind marbled rock roast, who produced it and brought it to the Eldin region. It uses its rock-covered legs to execute devastating attacks. The eyeball on its head may look vulnerable, but good luck reaching it atop this creature's massive body. It can be found in: Fire Temple.\n\nThe is a location in . Features and Overview The Fire Temple 1F is the base floor of the Fire Temple. Its entrance hall is blocked by a Gloom Rock, which can only be destroyed with Yunobo's assistance. When Link and Yunobo first arrive, they spot Zelda advancing to the center of the floor, which is barred by a gate.\n\ndiscern a voice telling them to come to a structure in the distance. Since the voice may be related to Zelda's location, Yunobo decides that they should follow it."),
            ]
        ),

        WalkthroughChapter(
            id: "lightning-temple",
            title: "Gerudo Town & the Lightning Temple",
            category: .mainQuest,
            icon: "bolt",
            sections: [
            WalkthroughSection(id: "lt-gerudo", title: "Reach Gerudo Town", content: "is a recurring location in . Features and Overview thumb|right|320px|The North Gate of Gerudo Town Gerudo Town is the primary settlement of the Gerudo Desert, and it consequently serves as the home of the Gerudo people. Since the Gerudo are a solely female race, they only allow women to enter the Town. When inside Gerudo Town, Link will not be subjected to the Heat or Freezing Climate of the Gerudo Desert.\n\nInitially, a total of three Side Quests can be found in Gerudo Town, those being \"Medicinal Molduga\", \"The Secret Club's Secret\", and \"Tools of the Trade\". \"The Seven Heroines\" Shrine Quest can also be obtained after Link is able to enter Gerudo Town.\n\nOverview During the \"Regional Phenomena\" Main Quest, Purah tasks Link with investigating strange occurrences throughout Hyrule in an effort to find Princess Zelda. After \"Tulin of Rito Village\", \"Yunobo of Goron City\", and \"Sidon of the Zora\" have all been completed, Purah will direct Link to visit Gerudo Town, since it is the only place he has yet to visit."),
            WalkthroughSection(id: "lt-riju", title: "Riju of Gerudo Town", content: "approaches Riju, the Secret Stone will suddenly shrink and rush before her. When she touches it, it will begin to glow, and a bright light will overtake both her and Link. The Spirit of Ardi, the Sage of Lightning, appears before them, and Riju recognizes her as the voice that has been calling out to them.\n\nneeds. Now able to repay Link for all the help he has given her, Riju asks if he wants to return to Gerudo Town. As the Sand Shroud disappears, Dalia, Kalani, Pearle, Nali, and Pritana can all be seen exiting the Gerudo Shelter. In the Royal Palace's Throne Room, Buliara smiles to herself as she looks toward the Lightning Temple.\n\nMakeela is a recurring character in . Biography Riju is the young Gerudo Chief, ruling over Gerudo Town after the untimely passing of her mother. Riju was her mother's only child, causing the duties of leading the Gerudo to fall to her. Riju resides in the Royal Palace, with her Bedroom being located on the second floor. At the time of , she is approximately 12 years old."),
            WalkthroughSection(id: "lt-yiga", title: "Infiltrate the Yiga Clan Hideout", content: "The , also known as the Gerudo Desert Hideout, is a recurring location in . Features and Overview The Yiga Clan Hideout is located in the Gerudo Highlands inside what remains of a Gerudo temple that was reclaimed as the secret base of the Yiga Clan and their leader, Master Kohga. It is hidden at the end of Karusa Valley in the Gerudo Desert.\n\nAll Blademasters will drop the torches they were carrying, which can Link can pick up if he is in desperate need of a Weapon. Being spotted can happen in both rooms, meaning Link may fight up to seven Blademasters and four Footsoldiers in the Hideout, as there are two Blademasters in the first room and five in the second.\n\nThe is a recurring location in . The Yiga Clan Hideout Hall goes unnamed in . Features and Overview The Yiga Clan Hideout Hall is a part of the Yiga Clan Hideout in the Gerudo Highlands. It is the Hideout's largest room, and it features the front entrance to Master Kohga's Room. A small storage room filled with Mighty Bananas can be found above the Hall.\n\nThe is a recurring location in . The Yiga Clan Hideout Chasm goes unnamed in and . Features and Overview The Yiga Clan Hideout Chasm is located behind the Yiga Clan Hideout in th"),
            WalkthroughSection(id: "lt-temple", title: "Lightning Temple — Puzzles", content: "The is a location in . Features and Overview The Lightning Temple 5F is accessible by riding the Updraft from the Room of Ascension. Four Statue equipped with Mirrors can be found on Rails in the central chamber of the floor. A ledge on the southwest side of the room gives way to the Room of Natural Light.\n\nThe is a location in . Features and Overview The Lightning Temple 2F is accessible from the Lightning Temple 1F's Room of Ascension. It leads to the Room of Light and Flame, which features a Battery inside a cage that cannot be opened from the outside. There is also a light-sensitive Switch attached to a Statue above the Room of Ascension.\n\nThe is a location in . Features and Overview The Lightning Temple 4F is accessible by a stairway above the Room of Ascension. There are two light-sensitive Switches attached to Statues on the floor. Additionally, there is Light Beam obscured by Stone Blocks and rotating semi-circular walls.\n\nThe is a location in . Features and Overview The Lightning Temple B1 is a winding pathway found directly across the entrance to the Lightning Temple 1F.\n\nLightcast Island is a location in . Features and Overview thumb|right|320px|alt= The surface of Lightcast Isl"),
            WalkthroughSection(id: "lt-boss", title: "Boss: Queen Gibdo", content: "is a Boss in . Characteristics Queen Gibdo is a massive, grotesque Gibdo who caused their infestation of the Gerudo Desert. Her wings are powerful enough to allow her to fly despite her large size. Unlike the Gibdos that she commands, she possesses eight limbs, typically using the first two pairs as arms while walking on the other four. One Queen Gibdo is responsible for the Sand Shroud affecting the Gerudo Region.\n\nQueen Gibdo is a Monster in Tears of the Kingdom. The ruler of the Gibdos and the culprit behind the sand shroud that plagued the Gerudo region, the Queen Gibdo is an agile beast who built a nest in the desert to spawn her drones en masse. Her tough exoskeleton deflects ordinary weapons. It can be found in: Lightning Temple.\n\nOutfits at Madame Couture's. There are eight bosses in , six of which are incarnations of Malice. These are Waterblight Ganon, Fireblight Ganon, Windblight Ganon, Thunderblight Ganon, Calamity Ganon, and Dark Beast Ganon. The other two are Master Kohga and Monk Maz Koshia, the latter of whom can only be challenged when Downloadable Content pack is active.\n\nare locations in . Features and Overview Boss Rematches are structures scattered across the Depths."),
            ]
        ),

        WalkthroughChapter(
            id: "master-sword",
            title: "The Master Sword",
            category: .mainQuest,
            icon: "sparkles",
            sections: [
            WalkthroughSection(id: "ms-tears", title: "The Dragon's Tears — All Memories", content: "Overview After Link views the Memory \"Where Am I?\" during \"Impa and the Geoglyphs\", Impa will appear nearby and ask him what is wrong. After hearing that Link was able to see a vision of the past, she theorizes that Princess Zelda could be connected to the Geoglyphs and their Dragon's Tears.\n\nat which point he disappears once more. With Recall, Link is able to reverse the gears within the Temple of Time, allowing him to access the upper chamber. There, he finds a Challenge Door, which will drain his Hearts as he pushes it.\n\nOverview At New Serenne Stable, Link can encounter Cado and his Donkey looking out toward the North Hyrule Plain. He is relieved to see that Link has reappeared after going missing, but he then asks where Zelda is. Upon hearing Link's explanation, he is shocked to hear that she is still unaccounted for. Cado suggests that Link speak with Impa, who is investigating the Geoglyph on the North Hyrule Plain.\n\nThe is a recurring character in . Biography The Light Dragon is a Dragon Spirit known for flying in the upper areas of the Sky. It is the form that Zelda takes after swallowing her Secret Stone of Time and undergoing the process of draconification, losing her mind and"),
            WalkthroughSection(id: "ms-rings", title: "Secret of the Ring Ruins", content: "Overview During the \"Find the Fifth Sage\" Main Quest, Purah asks Link to search for clues as to the remaining Sage's whereabouts among ruins from the ancient past. In Kakariko Village, he can find Paya and Tauro looking up at the Floating Ring Ruin.\n\nDracozu Lake. If it is daytime, Calip expresses his hope to find more clues, though he claims he needs to rest before joining Tauro. At night, Calip is worried that Tauro has yet to return, wondering if he is caught up in his investigation.\n\nthumb|right|320px|alt=Zelda rushing to Mineru's side.|Mineru after being poisoned by Gloom The Sages confronted Demon King Ganondorf, but failed to stop him, so Rauru sacrificed himself to seal Ganondorf for millennia. Although she and the other Sages survived, Mineru was gravely damaged by his Gloom in the battle and knew that her body would not last much longer.\n\nOverview After facing Phantom Ganon during the \"Crisis at Hyrule Castle\" Main Quest, Link and the Sages return to Purah and Lookout Landing, who is able to determine that Princess Zelda was making preparations for their fight against Demon King Ganondorf in the ancient past."),
            WalkthroughSection(id: "ms-dragon", title: "Reach the Light Dragon", content: "The is a recurring character in . Biography The Light Dragon is a Dragon Spirit known for flying in the upper areas of the Sky. It is the form that Zelda takes after swallowing her Secret Stone of Time and undergoing the process of draconification, losing her mind and sense of self in the process.\n\nhe successfully holds on, the Light Dragon will take Link higher into the Sky. The fur holding the Master Sword in place recedes, and Link is able to claim it once again. Afterwards, Link jumps from the Light Dragon's back as she flies past the Temple of Time. After Demon King Ganondorf turns into the Demon Dragon, the Light Dragon rushes to confront him in the Sky above Hyrule Castle.\n\nLight Dragon is a Monster in Tears of the Kingdom. A spirit has taken the form of this giant dragon inhabiting the upper reaches of the skies. It is named for its shining golden mane and gleaming scales. It looks divine as it soars through the sky, giving off a soft glow, and its presence is comforting somehow. It can be found in: Greater Hyrule.\n\nLight Dragon'S Horn is a Material in Tears of the Kingdom. A horn chipped off the Light Dragon.\n\nShard Of Light Dragon'S Spike is a Material in Tears of the Kingdom."),
            WalkthroughSection(id: "ms-obtain", title: "Obtain the Master Sword", content: "or in proximity to Malice, the blade glows with a blue aura. In this state, the Master Sword's power is doubled to 60. Unlike all other Weapons, it runs out of energy temporarily after a certain amount of uses instead of breaking. It is unusable in this state and will regain its energy after 10 minutes.\n\nPad. Obtaining the Master Sword is not required in order to face Demon King Ganondorf. When an Item or Object is fused with the Master Sword, it becomes a silhouette that disappears when the sword is not in use. Additionally, Zonai runes become visible on the blade. Unlike other weapons, Pelison at the Break-a-Part Shop cannot remove fused items from the Master Sword."),
            ]
        ),

        WalkthroughChapter(
            id: "hyrule-castle",
            title: "Hyrule Castle",
            category: .mainQuest,
            icon: "building.columns",
            sections: [
            WalkthroughSection(id: "hc-crisis", title: "Crisis at Hyrule Castle", content: "Overview Upon hearing Link's story during the \"To the Kingdom of Hyrule\" Main Quest, Purah determines that the events of the Upheaval must be connected to the mummy he and Zelda encountered Beneath Hyrule Castle. Since Link heard Zelda's voice, Purah believes that she could still be trapped below Hyrule Castle.\n\nthat their combined efforts will lead them to Zelda. At this point, \"Regional Phenomena\" will begin. thumb|right|320px|alt= A screenshot of the floating portion of Hyrule Castle during a Blood Moon. A figure that appears to be Princess Zelda stands on, the Sanctum visible behind her.|The impostor Zelda outside Hyrule Castle After completing \"Tulin of Rito Village\", \"Yunobo of Goron City\", \"Sidon of the Zora\", and \"Ri\n\nis a location in , serving as both the first and final area of the game. Features and Overview Beneath Hyrule Castle is a forbidden zone that descends into the very deepest part of Hyrule's Depths. A Stone Tablet in the Royal Hidden Passage indicates that the area beneath the castle was originally accessible through the passage."),
            WalkthroughSection(id: "hc-guidance", title: "Guidance from Ages Past", content: ", also known as Kaepora Gaebora when in his owl form, is a recurring character in . Biography Era of Chaos During the Era of Chaos and shortly before the Kingdom of Hyrule was established by the royal descendants of the goddess Hylia's mortal incarnation, Rauru built the Temple of Time over the remains of the Sealed Temple that was located deep within the Faron Woods in the Faron Province.\n\nfrees the other five Sages. He tells Link to meet \"someone\" waiting at the Temple of Time before facing Ganondorf. This person turns out to be Sheik, who reveals himself as none other than Princess Zelda, the seventh Sage. Unfortunately, by revealing herself to Link, Princess Zelda exposes herself to Ganondorf, who subsequently captures her and takes her to his Castle.\n\nnot able to completely destroy the Mirror, and the Sages reveal that the Mirror Shards are located in the Snowpeak Ruins, the Temple of Time, and the City in the Sky. While they believe that Link will be able to gather the Shards, they warn him about the dangerous power within them. When the Mirror of Twilight is repaired, the Sage of Spirit and the other Sages appear before Link and Midna again."),
            WalkthroughSection(id: "hc-ascent", title: "Ascend the Castle", content: "that their combined efforts will lead them to Zelda. At this point, \"Regional Phenomena\" will begin. thumb|right|320px|alt= A screenshot of the floating portion of Hyrule Castle during a Blood Moon. A figure that appears to be Princess Zelda stands on, the Sanctum visible behind her.|The impostor Zelda outside Hyrule Castle After completing \"Tulin of Rito Village\", \"Yunobo of Goron City\", \"Sidon of the Zora\", and \"Ri\n\nCastle Graveyard located at the very back of the structure. A passageway in Telma's Bar grants access to the Castle's Waterway, which connects to the Castle Sewers where the prison cells are located. It is here that Link first catches a glimpse of the colossal castle since he finds himself imprisoned early on in the game after he is transformed into a wolf.\n\nvarious traps; moreover, since the stairs leading to the upper floors have been destroyed, Link must use the Double Clawshots and the Spinner to successfully reach the fourth floor. The door on the fourth floor, which leads to the outside of Hyrule Castle and eventually to the throne room, is blocked off by another Darknut.\n\nThe Hyrule Castle Courtyard, also known as the Castle Courtyard, is a recurring location in ."),
            ]
        ),

        WalkthroughChapter(
            id: "final-battle",
            title: "The Final Battle",
            category: .mainQuest,
            icon: "crown",
            sections: [
            WalkthroughSection(id: "fb-gloom", title: "Gloom's Origin", content: "are recurring Bosses and Enemies in . Characteristics Gloom Spawn consist of a group of long, corpse-like arms, resembling the arms of the mummified Demon King Ganondorf. Each hand has an eye on its palm, and the group is surrounded by a moving patch of Gloom. Gloom Spawn appear in fixed locations across Hyrule's Surface and Depths, remaining hidden until Link approaches their spawn location.\n\nare a type of Enemy in . Characteristics Gloom-Wreathed Enemies are variations of Monsters found exclusively in the Depths. They are distinguished from their Surface counterparts by the Gloom emanating from their bodies. When Link is attacked by a Gloom-Wreathed Enemy, Link's maximum amount of Hearts will be reduced by Gloom damage.\n\nis an Added Effect in . Overview Gloom Resistance is an Added Effect that provides Link with fake, teal Hearts that take Gloom damage before the Heart Containers in his Life Gauge do. These fake Hearts automatically heal over time when Link is safe from Gloom, even in the Depths.\n\nis an Added Effect in . Overview Gloom Recovery is an Added Effect that restores Hearts that have been damaged by Gloom. This effect can be obtained by Cooking Sundelions or Sun Pumpkins."),
            WalkthroughSection(id: "fb-army", title: "The Demon King's Army", content: "The Demon King's Army is a Boss in . Characteristics The Demon King's Army is a large group of Gloom-Wreathed Monsters. They can first be seen during \"The Demon King's Army\" Memory, which plays when Link and the Sages encounter Demon King Ganondorf in Hyrule Castle. In the ancient past, the Demon King can be heard commanding his Army to attack Hyrule and its citizens.\n\nZelda once more to lead Link into Hyrule Castle's Sanctum, where Ganondorf reveals the true form of the impostor Zelda and sends Phantom Ganon to end Link's life. After Link defeats Phantom Ganon, Ganondorf notices that there is more to Link's powers than Rauru's Right Arm has gifted, he dissolves Phantom Ganon into tendrils of Gloom but the Six Sages defend Link from them.\n\nDemon King Ganondorf (2Nd Form) is a Monster in Tears of the Kingdom. The fearsome form that Demon King Ganondorf attained after unleashing the power of the secret stone. The ancient sages were no match for him and only barely managed to contain his devastating power. The gloom he produces is a corrosive substance so foul that it can wither anyone who touches it."),
            WalkthroughSection(id: "fb-king", title: "Boss: The Demon King", content: "Demon King Ganondorf is a recurring Boss in . Biography Demon King Ganondorf is the form assumed by Ganondorf after obtaining his Secret Stone, stolen from Sonia. After becoming the Demon King, he created a swarm of Monsters and attacked Hyrule Kingdom and its allies, which started the Imprisoning War. At the end of the War, the Six Sages confronted him.\n\nshots from the Demon King's Bow. If Link has the Master Sword, it can be used to deflect Gloom projectiles, while any other Weapon will be destroyed immediately if they connect with the Gloom. Ganondorf also has the ability to Perfect Dodge, even against Link's Parries. The Demon King is also capable of knocking Arrows away if Link attempts to repeatedly shoot him in the head with a Bow.\n\ngather behind Link, drawing their Weapons. As Link and the Sages fight the Demon King's Army, waves consists of Gloom-Wreathed Lizalfos, Gibdos, and Moblins will appear in succession. Once all four waves have been defeated, the wall of Gloom will dissipate, and Sidon reasons that Demon King Ganondorf must be there.\n\nGanondorf Dragmire is a recurring character and boss in . The original Gerudo form of Ganon, he shares the role of the main antagonist of"),
            WalkthroughSection(id: "fb-dragons", title: "The Dragon Showdown", content: "he successfully holds on, the Light Dragon will take Link higher into the Sky. The fur holding the Master Sword in place recedes, and Link is able to claim it once again. Afterwards, Link jumps from the Light Dragon's back as she flies past the Temple of Time. After Demon King Ganondorf turns into the Demon Dragon, the Light Dragon rushes to confront him in the Sky above Hyrule Castle.\n\nThe is a recurring character in . Biography The Light Dragon is a Dragon Spirit known for flying in the upper areas of the Sky. It is the form that Zelda takes after swallowing her Secret Stone of Time and undergoing the process of draconification, losing her mind and sense of self in the process.\n\nThe is the final Boss in . It is the form attained by Demon King Ganondorf when, in a final attempt to destroy Link, he sacrifices himself by swallowing his Secret Stone of Darkness to irreversibly transform into a Dragon. By permanently losing his own self through the transformation, no trace of Ganondorf's original form remains. Biography Link defeats Demon King Ganondorf in Gloom's Origin, Beneath Hyrule Castle.\n\nOverview After Link views the Memory \"Where Am I?\" during \"Impa and the Geoglyphs\", Impa will ap"),
            ]
        ),

        WalkthroughChapter(
            id: "shrines",
            title: "Shrines",
            category: .sideContent,
            icon: "diamond",
            sections: [
            WalkthroughSection(id: "shr-sky", title: "Sky Islands Shrines", content: ", designated by the trial name The Ability to Rise, is a Shrine of Light in . Entrance to the Shrine The Gutanbac Shrine is located in the eastern part of the Garden of Time on the Great Sky Island between the entrances to the Bottomless Cave. In order to enter the Shrine of Light, Link must interact with the Gutanbac Shrine's entrance.\n\n, designated by the trial name The Ability to Rewind, is a Shrine of Light in . Entrance to the Shrine The Nachoyah Shrine is located above the Room of Awakening on the Great Sky Island. After Link enters the Temple of Time and receives the Recall ability from Zelda, the Spirit of Rauru guides him to the Nachoyah Shrine to receive the Great Sky Island's fourth Light of Blessing.\n\n, designated by the trial name The Ability to Create, is a Shrine of Light in . Entrance to the Shrine The Ukouh Shrine is located in the western part of the Garden of Time on the Great Sky Island, due west of the Temple of Time. In order to enter the Shrine of Light, Link must interact with the Ukouh Shrine's entrance.\n\nThe , designated by the trial name A Flying Device, is a Shrine of Light in . Entrance to the Shrine The Jirutagumac Shrine is located within the spherical Sky"),
            WalkthroughSection(id: "shr-eldin", title: "Eldin & Akkala Shrines", content: "The is a location in . Features and Overview The South Eldin Sky Archipelago is a collection of Sky Islands that can be found in the southern part of the Eldin Canyon Sky. There are two sets of Mine Cart Tracks that run through the Sky Islands beginning at the western Island then traveling through the southern Island before arriving at the eastern Island.\n\nThe , also known as , is a recurring location in . Features and Overview In , the Bridge of Eldin is a bridge found north of Kakariko Village. It crosses a deep gorge where Zora's River runs through, essentially connecting the Eldin Province to a path leading to the Lanayru Province. It also serves as the main access road to the Hidden Village.\n\nis a recurring location in . Features and Overview Eldin's Flank is an expansive cliff in the northern part of Eldin Canyon. It sits at the very edge of northern Hyrule, bordering a vast pit that serves as the end of the kingdom. The Flank sits on the other side of a mountain range that slopes downward from Death Mountain.\n\n, also known as the Eldin Region, is a recurring Region in . Features and Overview Eldin is a vast Region in northeastern Hyrule."),
            WalkthroughSection(id: "shr-lanayru", title: "Lanayru & Necluda Shrines", content: "The is a recurring location in . Features and Overview The Lanayru Promenade is located in East Necluda. It has been left in ruins after the Great Calamity with several walkways being either flooded or destroyed. The Lanayru Road - East Gate and Lanayru Road - West Gate serve as exits for the Promenade, and Lanayru Road runs along its northern wall.\n\nis a recurring location in . Features and Overview Lanayru Road is an unmarked road that passes through East Necluda and Mount Lanayru. It starts at the Lanayru Road - West Gate, runs along the northern side of the Lanayru Promenade, and continues under the Lanayru Road - East Gate before ending on the western side of the Naydra Snowfield. The Lanayru Road South Cave is named after it. Lanayru Road returns in .\n\nThe is a recurring location in . Features and Overview The Lanayru Road - West Gate is located between East Necluda and the Lanayru Great Spring. It is the crossroads leading from Kakariko Village, Rabia Plain, and the Lanayru Promenade. The area is full of long Grass, and Ore Deposits can be found on the sides of the surrounding cliffs.\n\nThe is a recurring location in . Features and Overview The Lanayru Sea was a treacherous ocean t"),
            WalkthroughSection(id: "shr-faron", title: "Faron Shrines", content: "The , also stylized as the Faron High Road, is a recurring location in . The Faron Highroad goes unnamed in . Features and Overview Faron Highroad is an expansive road that begins in the Taobab Grassland in the Gerudo Highlands, continues into the Faron Grasslands and West Necluda, then ends at Lurelin Village in East Necluda.\n\n, also known as the Southern Wood, and the Skulltula Forest, is a recurring location in . As its name suggests, Faron Woods is part of and makes up a large majority of the overall Faron Province. It is home to one of the province's two protectors, Faron the Spirit of Light. The other protector from , Faron the Water Dragon, is located in the nearby Lake Floria. Faron Woods was known as the Kokiri Forest in .\n\nThe , designated by the trial name Wings on the Wind, is a Shrine of Light in . Entrance to the Shrine The Apogek Shrine can be found on the southern edge of Ja'Abu Ridge in the Lanayru Great Spring. It corresponds to the Kegopa Lightroot in the Depths. Themes and Navigation The Shrine is a two-room traversal shrine built around the Wing. The first room sees Link using a Wing to move an Ancient Orb across a gap."),
            WalkthroughSection(id: "shr-central", title: "Central Hyrule Shrines", content: "is a recurring Region in . Features and Overview Central Hyrule is the central Region of Hyrule, containing the Great Plateau and Hyrule Field. The Region was severely damaged in the Great Calamity a hundred years prior to the events of . Link begins his quest in this Region after waking up in the Shrine of Resurrection on the Great Plateau.\n\nThe , designated by the trial name Rauru's Blessing, is a Shrine of Light in . Entrance to the Shrine The Jinodok Shrine can be found within the South Hyrule Sky Archipelago in the Central Hyrule Sky. Themes and Navigation thumb|right|320px|The interior of Jinodok Shrine The Jinodok Shrine is a simple Shrine of Light with the sole purpose of rewarding Link for reaching it.\n\nThe , designated by the trial name Shape Rotation, is a location in . Entrance to the Shrine The Jiosin Shrine is a Shrine of Light on the Surface. It is located just outside the Hyrule Field Chasm in Central Hyrule. It corresponds to the Nisoij Lightroot in the Depths. Themes and Navigation The Jiosin Shrine focuses heavily on the precise use of the Ultrahand ability to manipulate the orientation of Objects.\n\nare locations in . Features and Overview Shrines of Light are sacred p"),
            WalkthroughSection(id: "shr-gerudo", title: "Gerudo & Rito Shrines", content: "The are a recurring location in . Features and Overview The West Gerudo Ruins are located throughout the West Barrens of the Gerudo Desert. They are a scattered set of Gerudo Ruins, bearing the Gerudo architectural style distinct from the rest of Hyrule. Several of the Swordswomen Statues are situated within the Ruins.\n\nThe is a location in . Features and Overview The East Gerudo Sky Archipelago is located in the Gerudo Highlands Sky. It is a cluster of Sky Islands that are particularly abundant with Accented Pigeons. The southwestern Sky Island features a pool of Water and an eastward-facing ramp. A couple Vehicles and spare Zonai Devices can be found here, with one Vehicle loaded onto the ramp.\n\nis a recurring location in . Features and Overview Gerudo Canyon Stable is a Stable located at the western end of Gerudo Canyon in the Gerudo Highlands. The Stable is managed by Piaffe, with Pirou being employed as a worker. The Kay Noh Shrine sits on a cliff south of the Stable, and the main entrance to the Gerudo Desert, the Gerudo Desert Gateway, can be found to the west.\n\nThe , also known as the Western Desert, is a recurring location in ."),
            WalkthroughSection(id: "shr-depths", title: "Depths Shrines", content: "The Depths are a location in . Features and Overview The Depths are a colossal network of caverns extending deep underneath Hyrule. They are accessed via the Chasms present on the surface, which are easily identified by the Gloom surrounding them. The Depths are extremely dark, making items that create light such as Brightbloom Seeds, Giant Brightbloom Seeds, or Lights valuable when exploring them.\n\nThe are a location in . Features and Overview The Gerudo Desert Depths are an area in the Depths located below the Gerudo Desert on the Surface. They are generally flat, featuring no major hills or valleys. They are also noted by Master Kohga to be Sandy. There are a total of eight Lightroots spread throughout the Gerudo Desert Depths.\n\nthe Hyrule Field Chasm. Josha expresses her excitement to see Link's Picture, and she asks him to take care of Robbie as well. Following this conversation, \"Camera Work in the Depths\" will begin. At the Hyrule Field Chasm, Link will discover that Robbie has already descended into the Depths. At the bottom of the Chasm, he will find Ponnick looking for Robbie.\n\nOverview \"A Mystery in the Depths\" becomes available after one of the Main Quests associated with \"Re"),
            ]
        ),

        WalkthroughChapter(
            id: "side-quests",
            title: "Side Quests",
            category: .sideContent,
            icon: "list.bullet.clipboard",
            sections: [
            WalkthroughSection(id: "sq-stables", title: "Stable Quests", content: "The is a recurring location in . Features and Overview The Dueling Peaks Stable is a Stable located in West Necluda, situated beside the road running north from the Big Twin Bridge, east of the Dueling Peaks themselves. The Ha Dahamar Shrine is in a shallow pool of Water between the Stable and the Dueling Peaks, providing a convenient Travel Gate to the Stable when activated.\n\nOverview When Link examines the Empty Frame at Highland Stable, Padok will notice his interest. He reveals that the Stable Association has given it to the Stable in order to display a Picture. Having heard a rumor about the Giant White Stallion, Padok wants to display a Picture of it.\n\nOverview When Link inspects the Empty Frame at Riverside Stable, Ember will notice him doing so. He explains that it was provided by the Stable Association so that he could display a Picture for visitors to enjoy. Ember has decided that he wants to hang a Picture of a Great Goddess Statue.\n\nis a recurring location in . Features and Overview East Akkala Stable is a Stable located on the North Akkala Foothill in Deep Akkala, It is managed by Rudi, and the Katosa Aug Shrine can be found across the road."),
            WalkthroughSection(id: "sq-addison", title: "Addison's Hudson Signs", content: "is a recurring character in . Biography Gaddison is a Zora guard for Zora's Domain who can be found guarding the eastern bridge, wielding a Zora Spear. In her youth, Gaddison was part of the Big Bad Bazz Brigade with Bazz and Rivan. Before the Great Calamity, Link would play with her and her friends. When Link first approaches Gaddison, she reports that the east gate to Zora's Domain is clear.\n\nis a recurring location in . Ash Swamp goes unnamed in . Features and Overview Ash Swamp is located in West Necluda. Like the adjacent Blatchery Plain, Ash Swamp is composed of generally flat land with tall Grass and ruined buildings. During the second Great Calamity, Guardians made their way through Ash Swamp on their way to Fort Hateno.\n\nis a recurring character in . Biography Bolson is the president of Bolson Construction, a company that only hires people whose names end in \"-son\". If Link asks Bolson who he is, he will recite Bolson Construction's signature theme and dance, only to be disappointed by the realization that Link does not recognize it.\n\nis a recurring location in . Features and Overview Mabe Prairie is located northeast of the Mabe Village Ruins in Hyrule Field."),
            WalkthroughSection(id: "sq-zelda", title: "Potential Princess Sightings", content: "The , also known as the Froggy Clothes, is an Armor Set in . Location and Uses The Froggy Armor consists of the Froggy Hood, the Froggy Sleeve, and the Froggy Leggings. It can initially be found at the Lucky Clover Gazette. At the start of the \"Potential Princess Sightings!\" Side Adventure, Traysi offers the Armor Set to Link as an incentive for his help investigating the disappearance of Zelda.\n\nThe is a location in . Features and Overview The Gerudo Canyon Well can be found beside Gerudo Canyon Stable in the Gerudo Highlands. It has an interior that Link is able to access, which consists of a small pond. There is a pile of Hard Sediment along the eastern wall that, when broken, reveals a second chamber infested by Monsters.\n\nThe is a location in . Features and Overview The Lucky Clover Gazette is a Newspaper company owned by Traysi. After the Extreme Cold Snap caused by the Upheaval drove customers away from Rito Stable, most of its residents left and sought a home elsewhere while Traysi bought the place from Galli at a dubious price. She enlisted the Rito Penn and her sisters Juannelle and Douma to serve as its staff.\n\nis a Stable in . Features and Overview New Serenne Stable is a Sta"),
            WalkthroughSection(id: "sq-lurelin", title: "Lurelin Village Restoration", content: "The , also known as the , is a recurring location in . Location and Uses The Merchant Boat is located at the end of the longest Dock in Lurelin Village. It is a General Store run by Mubs, focusing on selling Fish that can be found in the surrounding Necluda Sea. The Merchant Boat itself carries Mubs' supplies, including extra Armored Porgies and Mighty Porgies.\n\nis a recurring location in . Overview Lurelin Village is a seaside town located at the western end of the Faron Highroad in East Necluda. Many of its Houses are simple wooden huts, which have been built around the Palm Trees indigenous to the area. The residents also make use of wooden platforms and Docks, one of which is located along a freshwater pond on the western end of the Village.\n\nOverview After completing the \"Village Attacked by Pirates\" and \"Lurelin Village Restoration Project\" Side Adventures, Link can find Garini at the dock in Lurelin Village. He seems defeated, and he tells Link that with his Boat gone, he cannot open the Lurelin Village Store. Unfortunately, he cannot borrow one, because all the Boats in the village got washed out when the Monsters attacked."),
            WalkthroughSection(id: "sq-phantom", title: "The Phantom Ganon Armor", content: "Phantom Ganon first appears as the boss of Hyrule Castle. In order to defeat it, the Links must hit its energy balls back and forth with the Sword. Once stunned, it is vulnerable to slashes from the Sword. Phantom Ganon appears once again as the boss of the Temple of Darkness; however, it now summons clones to its aid.\n\nspreading Gloom around them to drain Link's maximum health and reduce his room to maneuver. When defeated, they will drop their Weapons and Dark Clumps. If they spot Link in a location they cannot reach, they will equip Demon King's Bows to attack from a distance. Attacks from a Phantom Ganon's melee Weapon or the Demon King's Bow will destroy any Zonai Devices they come into contact with.\n\nPhantom Ganon is a Monster in Tears of the Kingdom. Though it may walk on two legs, this creature is undeniably monstrous in appearance. A sinister aura permeates the air around it. You know little of its attributes or behavior, but its strength and weapon mastery make it a formidable foe. It was first sighted after the Upheaval. Its identity and origins are shrouded in mystery. It drops: dark clump."),
            ]
        ),

        WalkthroughChapter(
            id: "side-adventures",
            title: "Side Adventures",
            category: .sideContent,
            icon: "figure.walk",
            sections: [
            WalkthroughSection(id: "sa-sages", title: "Sage's Will Locations", content: "be used to strike Enemies from afar with any Bow, except for the Twilight Bow and Bow of Light, which only shoot Light Arrows. Shooting an Enemy in the head with an Arrow will inflict double damage. If an Enemy is scouting on a lookout post, Link can shoot them in the head to instantly defeat them. Link can shoot Arrows while riding a Horse and from atop the Master Cycle Zero.\n\nThe , also known as the Western Desert, is a recurring location in . Features and Overview The Gerudo Desert is found in the Desert Province in , located in the corner of Hyrule. Although called Gerudo Desert, the Gerudo themselves do not appear in . The Gerudo Desert is completely cut off from the rest of Hyrule after being abandoned years ago.\n\nthem, or used to upgrade Potions at the Infusion Shop. Insects are abundant on Bug Rock in the Thunderhead. At Bug Rock, Stritch runs a mini-game called Bug Heaven during the day, which involves catching specific Bugs within a certain time limit. Beedle owns a pet Bug called the Horned Colossus Beetle. At some point during the game, Beedle loses his Bug. Link must regain it from Stritch by completing Bug Heaven."),
            WalkthroughSection(id: "sa-dispelling", title: "Dispelling Gloom", content: "are a type of Enemy in . Characteristics Gloom-Wreathed Enemies are variations of Monsters found exclusively in the Depths. They are distinguished from their Surface counterparts by the Gloom emanating from their bodies. When Link is attacked by a Gloom-Wreathed Enemy, Link's maximum amount of Hearts will be reduced by Gloom damage.\n\nis an Added Effect in . Overview Gloom Resistance is an Added Effect that provides Link with fake, teal Hearts that take Gloom damage before the Heart Containers in his Life Gauge do. These fake Hearts automatically heal over time when Link is safe from Gloom, even in the Depths.\n\nare recurring Bosses and Enemies in . Characteristics Gloom Spawn consist of a group of long, corpse-like arms, resembling the arms of the mummified Demon King Ganondorf. Each hand has an eye on its palm, and the group is surrounded by a moving patch of Gloom. Gloom Spawn appear in fixed locations across Hyrule's Surface and Depths, remaining hidden until Link approaches their spawn location.\n\nis an Added Effect in . Overview Gloom Recovery is an Added Effect that restores Hearts that have been damaged by Gloom. This effect can be obtained by Cooking Sundelions or Sun Pumpkins."),
            WalkthroughSection(id: "sa-construct", title: "Steward Construct Quests", content: "are a recurring mechanic in . Overview Throughout , Link can obtain three types of Quests by exploring and interacting with characters. These are Main Quests, Side Quests, and Shrine Quests. Progress on all three types of Quests is tracked through the Adventure Log. Main Quests, Side Quests, and Shrine Quests all return in . Alongside these, a new type of Quest known as Side Adventures can be found as well.\n\nhelmet, help lagging behind Warriors catch up with the currently highest leveled Warrior. and the Kochi Dye Shop, marked with a vial, changes the color of Link's clothes, with the Rupees depending on the dye. Improve Services Quests, which gives Link and co. discounts, as well as more services with the Blacksmith Guild, and additional dye options for the Dye Shop. These are marked with a building & an up arrow.\n\nare a recurring mechanic in . Overview Shrine Quests are a variety of quest accessed from the Adventure Log. Each one is linked to the discovery of an Ancient Shrine, some of which are inaccessible without involvement with the Shrine Quest. Some Shrine Quests, such as \"The Silent Swordswomen\" instead guide Link to an already-existing but difficult to access Ancient Shrine."),
            ]
        ),

        WalkthroughChapter(
            id: "collectibles",
            title: "Collectibles & Completion",
            category: .sideContent,
            icon: "star.circle.fill",
            sections: [
            WalkthroughSection(id: "col-korok", title: "Korok Seeds (1000)", content: "Korok Seeds are recurring Items in . Location and Uses Korok Seeds are given by Koroks when they are found throughout Hyrule. They possess a distinct smell. When Link receives his first Seed, he is asked to return it to the Korok Hestu. Korok Seeds are actually the beads used in Hestu's Maracas. When first found, Hestu asks Link to retrieve his Maracas from a group of Bokoblins nearby.\n\nas rewards for completing Challenge Quests centered around Hestu's involvement. Once a Warrior locates a Korok, it will give them a Korok Seed. Koroks who Warriors find will remain out in the open as a way to help players keep track which Koroks they have found. There is a total of 175 Korok Seeds found in the game, and are divided as such: 122 Korok Seeds are hidden within the 20 Story missions.\n\nare a recurring mechanic in . Overview Korok Seed Puzzles are a type of Puzzle that reward Korok Seeds upon completion. While most are relatively simple, others may require precise timing or skill. Korok Seed Puzzles are the hiding places of Koroks, who will grant Link a Seed when found.\n\nis a recurring character in . Biography When Link first encounters a Korok, it will believe that it has been found by Hestu b"),
            WalkthroughSection(id: "col-bubbul", title: "Bubbulfrogs", content: "Bubbulfrog is a Creature in Tears of the Kingdom. These mysterious creatures dwell in caves all around the world. They like to stay hidden and will spew bubbles when threatened. When overcome, they disappear and leave behind mysterious objects. It drops: bubbul gem.\n\nBubbul Gems are Items in . Location and Uses Bubbul Gems are Key Items that are dropped by defeated Bubbulfrogs, which are Creatures found in the Caves scattered throughout Hyrule. Each Cave has only one Bubbulfrog, meaning only one Bubbul Gem can be acquired per Cave.\n\nKoltin's Stall is a location in . Features and Overview Koltin's Stall is a Shop run by Koltin, who will trade various Armor and Monster Parts to Link in exchange for Bubbul Gems. Initially, Koltin's Stall can be found in front of the Pico Pond Cave. There, Koltin and his brother Kilton are looking for a Bubbulfrog so that Koltin can acquire and eat a Bubbul Gem in order to become \"a Satori\".\n\nKoltin is a character in . Biography Koltin is the brother of Kilton. He trades various Armor and Monster Parts to Link in exchange for Bubbul Gems, believing that consuming them will allow him to become \"a Satori\"."),
            WalkthroughSection(id: "col-bargainer", title: "Bargainer Statues", content: "Bargainer Statues are characters in . Biography Bargainer Statues are sapient Statues that are predominantly found in the Depths. Their purpose is to deliver Poes to the afterlife. Link can speak with most of them to trade Poes for rare Materials, Armor, and Equipment. The Bargainer Statue at the entrance to the Great Plateau cannot be traded with.\n\nand must be defeated to retrieve the fire. They can only be seen and attacked as Wolf Link, and carry Poe Souls which can be ripped from them. The last Poe has the strategy of duplicating itself and encircling Link. Along with the Imp Poe encountered in Jovani's house, they are the only Poes required to be defeated in the game. In , Poes have a radically different look in comparison to their earlier incarnations.\n\nThe Depths are a location in . Features and Overview The Depths are a colossal network of caverns extending deep underneath Hyrule. They are accessed via the Chasms present on the surface, which are easily identified by the Gloom surrounding them. The Depths are extremely dark, making items that create light such as Brightbloom Seeds, Giant Brightbloom Seeds, or Lights valuable when exploring them."),
            WalkthroughSection(id: "col-bosses", title: "Hinoxes, Taluses & Moldugas", content: "The is an Item in . Location and Uses After completing the Side Quests \"WANTED: Hinox\", \"WANTED: Molduga\", \"WANTED: Stone Talus\", \"Unknown Huge Silhouette\", \"Unknown Sky Giant\", and \"Unknown Three-Headed Monster\", Link will be able to talk to Gralens about Hinoxes. If he has defeated all 68 Hinoxes, Gralens will reward him with the Hinox Monster Medal.\n\nare recurring Items in . Location and Uses Hinox Guts are dropped by all three varieties of Hinoxes when defeated. As is the case with other Monster Parts, they can be cooked in a Cooking Pot with critters to make Elixirs. They can also be used to make Yellow Dye at the Kochi Dye Shop or exchanged for Mon with Kilton at the Fang and Bone.\n\nare recurring Items in . Location and Uses Hinox Toenails are Monster Parts that are dropped by all types of Hinoxes when they're killed. They're as thick as a plate of armor and can be cooked with critters in a Cooking Pot to make Elixirs. Alternatively, they can be sold to Kilton at the Fang and Bone for Mon or used as an ingredient for Brown Dye at the Kochi Dye Shop.\n\nare recurring Items in . Location and Uses Hinox Teeth are Monster Parts dropped by Hinoxes and Stalnox upon their defeats."),
            WalkthroughSection(id: "col-dragons", title: "Dragon Parts Farming", content: "The is a recurring character in . Biography The Light Dragon is a Dragon Spirit known for flying in the upper areas of the Sky. It is the form that Zelda takes after swallowing her Secret Stone of Time and undergoing the process of draconification, losing her mind and sense of self in the process.\n\nare a recurring class of Item in . Dragon Parts go unnamed in . Location and Uses Dragon Parts are a type of Material that can be obtained from shooting Dragons with Arrows. Depending on where Link shoots, he will obtain either a Scale, a Claw, a Fang Shard, or a Horn Shard. Dragon Parts can be given to a Great Fairy in order to Enhance pieces of Armor.\n\nLight Dragon'S Horn is a Material in Tears of the Kingdom. A horn chipped off the Light Dragon. Its gentle glow has a calming effect, and it has a mysterious healing power when attached to a weapon.\n\nThe is the final Boss in . It is the form attained by Demon King Ganondorf when, in a final attempt to destroy Link, he sacrifices himself by swallowing his Secret Stone of Darkness to irreversibly transform into a Dragon. By permanently losing his own self through the transformation, no trace of Ganondorf's original form remains."),
            ]
        ),

        WalkthroughChapter(
            id: "tips-and-tricks",
            title: "Tips & Tricks",
            category: .reference,
            icon: "lightbulb",
            sections: [
            WalkthroughSection(id: "tt-combat", title: "Combat Tips", content: "shots from the Demon King's Bow. If Link has the Master Sword, it can be used to deflect Gloom projectiles, while any other Weapon will be destroyed immediately if they connect with the Gloom. Ganondorf also has the ability to Perfect Dodge, even against Link's Parries. The Demon King is also capable of knocking Arrows away if Link attempts to repeatedly shoot him in the head with a Bow.\n\nare recurring abilities in . Overview Link can perform a Flurry Rush in after he successfully performs a Perfect Dodge. According to \"Daruk's Training Journal\", Flurry Rush is a result of Link's perception of Time down when he focuses. While focusing, Link is capable of performing multiple hits in quick succession with his Weapon in a short period of time.\n\ntheir reunion at the top of his Castle could only be fate. As he has already claimed Princess Zelda's Triforce of Wisdom, he quickly attacks Link and steals his Triforce of Courage. After reassuring Link that he only wishes to take hold of the Triforce of Courage, he reunites the completed Triforce and begins to wish for the rays of the Sun to shine on Hyrule once more so that he may claim it."),
            WalkthroughSection(id: "tt-building", title: "Ultrahand & Building", content: "Ultrahand is a recurring ability in . Overview Ultrahand is an Ancient Power that Link obtains from Rauru in Ukouh Shrine. It allows Link to stick Objects together or move them. When Ultrahand is used, Link has the option to move Objects around or rotate them either vertically or horizontally. If Link moves an Object close to another one, he can bind them together with a green viscous substance.\n\nOverview \"A Mystery in the Depths\" becomes available after one of the Main Quests associated with \"Regional Phenomena\" has been completed. At Lookout Landing, Link will find Josha while Tauro arguing about whether he should be involved in Chasm Research. Tauro wants to help Josha, but she thinks that he should finish investigating the Ring Ruins first.\n\nis a recurring ability in . Location and Uses Autobuild is an Ancient Power that Link can use with his Right Arm, which can be found in the Great Abandoned Central Mine. It allows Link to generate Objects constructed with Ultrahand automatically, expending Zonaite should the component parts needed to build the Object not be available in his nearby surroundings.\n\nThe Depths are a location in . Features and Overview The Depths are a colossal networ"),
            WalkthroughSection(id: "tt-rupees", title: "Farming Rupees", content: "is a recurring character in . Biography Brokka travels between Dueling Peaks Stable and Kakariko Village, carrying a Hunter's Shield and a Traveler's Sword. When she reaches Kakariko Village, Brokka will rest at the Shuteye Inn before continuing her journey. At Dueling Peaks Stable, she sits at the table inside before heading out. Brokka is very passionate about Gems, often singing Gem-themed lyrics while walking.\n\nis a recurring character in . Biography Hagie is a Hylian who moves to Tarrey Town with his family after the completion of the \"From the Ground Up\" Side Quest. During the day, he sits at the edge of town, overlooking Lake Akkala and the Torin Wetland. When Link first speaks to him, Hagie asks what his deal is.\n\n, also known as , are items in . They are the unit of Currency within most games, in circulation in the lands of Hyrule, the Dark World, Koholint Island, Termina, Labrynna, Holodrum, the Great Sea, the World of the Ocean King, New Hyrule, Skyloft, Lorule and Hytopia. They resemble hexagonal gemstones, come in many colors and sizes, and are most often stored within a Wallet.\n\nis a recurring character in . Biography Agus is a Merchant who lives in Hateno Village in East N"),
            WalkthroughSection(id: "tt-cooking", title: "Cooking & Elixirs", content: "a base 5% chance to occur per unique Material in the dish. Some Materials will further increase the rate on top of that, but it will only be calculated in once and only by the highest chance present. Cooking between 11:30 and 12:15 on the night of a Blood Moon will guarantee a bonus. Critical bonus chance caps at 100%; no more than one bonus can be gained per Recipe.\n\nThis article details the Cooking mechanisms specific to . For the Cooking mechanisms of , see Cooking in . __TOC__ Overview Cooking is a mechanic in that allows Link to combine Ingredients in order to make Meals. Although Cooking remains mostly unchanged from how it was in , new Ingredients can be found around Hyrule, most of them with their own Added Effects.\n\nThe is a recurring location in . The Common Cooking Area goes unnamed in . Features and Overview The Common Cooking Area is a part of Kakariko Village in West Necluda. It features a Cooking Pot, the Campfire under which can be lit in order to prepare Food. Two Jars at the side of the structure can be broken for supplies. In the evening, Olkin and Mellie will head to the Common Cooking Area to make dinner."),
            WalkthroughSection(id: "tt-armor", title: "Best Armor Sets", content: "are recurring Items in . Armors go unnamed in . They are pieces of Clothing and protective covering that Link can wear. Location and Uses Suits of Armor can be found in Hyrule Castle. They are equipped with Spears. Armor serves a variety of purposes, primarily to provide Link with defensive padding, allowing him to endure more damage. Damage numbers are shown numerically in , albeit indirectly.\n\nThe is a recurring Item in . Location and Uses The Rubber Armor can be acquired in the Toh Yahsa Shrine after completing the \"Trial of Thunder\" Shrine Quest on the Thundra Plateau. It provides Link with three Defense and one level of Shock Resistance. It can be enhanced by a Great Fairy and Dyed at the Kochi Dye Shop.\n\nZora Armors, also known as Zora Tunics, are recurring Items in . Location and Uses In , the Zora Tunic allows Link to breathe underwater. It is mostly used in conjunction with the Iron Boots and is essential when exploring the Water Temple. Unlike the Goron Tunic, it does not offer any defense bonuses. The Tunic can be stolen by a Like Like if Link is still wearing it when he gets spit out.\n\nare recurring Items in . Location and Uses Armoranths grow on Hyrule Ridge and in the Akkal"),
            ]
        ),

        WalkthroughChapter(
            id: "equipment",
            title: "Weapons & Equipment",
            category: .reference,
            icon: "shield",
            sections: [
            WalkthroughSection(id: "eq-weapons", title: "Best Weapon Fusions", content: ", also known as , and Bone Weap. Prof., is a recurring Set Bonus in . Overview Bone Atk. Up is a Set Bonus that increases the attack power of bone Weapons and Bows by 80%. This boost stacks multiplicatively with the Attack Up Effect. The following Weapons are considered to be bone Weapons or Bows in : Bone Atk. Up is granted by the Radiant Attire (★★) and the Phantom Ganon Set.\n\nand blunt Weapons will not. Heavy two-handed Weapons can disrupt an opponent's balance if they brandish a Shield, allowing for Link to knock their Shield out of their hand and bypass their defenses. Apart from their melee uses, Link can throw his Weapons at his enemies."),
            WalkthroughSection(id: "eq-shields", title: "Shield Surfing & Fusions", content: "In , Link can perform a Deflect by pressing the 'A' button while guarding by holding 'ZL'. This move will bash enemies and even cause damage as a slash attack when used with any type of Lynel Shield. Similar to the Shield Bash in , Link can perform a Perfect Guard by Deflecting just as an enemy's attack lands. This acts as a parry and temporarily stuns the enemy.\n\n, also stylized as Shield-Surfing, is a recurring ability in . Overview To perform Shield Surfing, Link can jump on any of his Shields and ride down the slopes of Snow-, Sand-, or Grass-covered mountains and hills as though it were a . Different Shields have different frictions and speeds, as do different surfaces.\n\nare recurring Items in . Royal Shields go unnamed in . Location and Uses Chief among metal Shields are the Royal Shields, whose Durability and defensive power outshine many others. Before the Great Calamity, these Shields were issued to the immediate guard detail of the Royal Family of Hyrule. hey belong to the Royal Gear equipment archetype, a series of Weapons associated with the Royal Family.\n\nare Items in . Location and Uses Emblazoned Shields are Shields featuring a traditional design from the Necluda Region."),
            WalkthroughSection(id: "eq-bows", title: "Bow & Arrow Types", content: ", also known as , and , are recurring Items in . Location and Uses The Bow allows Link to fire Arrows as its main ammunition, allowing him to snipe Enemies and faraway objects such as Switches. Being a staple item in , the Bow is almost always found in a Dungeon. Typically the item is often guarded by a Sub-Boss, most commonly within the console Zelda games with a few exceptions.\n\nit one of the most expensive items in The Legend of Zelda series. It can, however, simply be stolen. The Bow becomes available once Link has bought the Deluxe Shovel from the store. Like the Bow in , the Bow is able to inflict heavy damage onto most Enemies, and in some cases is one of the very few items that can damage certain Enemies, such as the Armos who are normally invincible to the Sword.\n\nRainbow Sparrow is a Creature in Tears of the Kingdom. These small birds hail from the Faron region. As the name suggests, their feathers are more colorful than other sparrows', which has made them a favorite among dilettantes. They feed on small rain-forest insects, but the omnivore in them loves nuts as well. It can be found in: Faron Grasslands, East Necluda. It drops: chickaloo tree nut."),
            WalkthroughSection(id: "eq-special", title: "Unique & Unbreakable Weapons", content: "at Lv.50 (Min-Max) Description One handed weapon(Master Sword Tier) Hylian Shield Knight's Bow 34-34 72-72 110-110 190-190 The Legendary sword that seals the darkness. Its blade gleams with a sacred luster that can oppose the Calamity. Only a hero chosen by the sword itself may wield it.\n\na certain point, Link receives a Letter stating that his Shop just opened. Link can get Beedle's attention from then on by blowing the Spirit Train's Train Whistle when he is nearby. He will then land, allowing Link to stop by it like any other Station. Link can get Beedle's Club Membership Cards, allowing him to save up a point for every ten Rupees spent.\n\nis a character in . Biography Cece is a famous fashion designer in Hateno Village who has taken over her family's clothing store, the Ventest Clothing Boutique. Cece's designs are known for incorporating the use of Mushrooms, which now adorn the Village.\n\n, also known as , and , are recurring Enemies in . They are gelatinous creatures of living slime or jelly, often depicted with facial features. Chuchus come in a wide variety of colors and types, with some having different traits and behaviors depending on their color."),
            ]
        ),

    ]

    static func chapters(for category: ChapterCategory) -> [WalkthroughChapter] {
        chapters.filter { $0.category == category }
    }
}
